# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:lts

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn install
          - yarn build
  branches:
    develop:
      - step:
          name: build and test
          caches:
          - node
          script: # Modify the commands below to build your repository.
          - yarn install
          - yarn build
          - yarn test:cov
      - step:
          name: deploy with tag
          script:
            # - apt-get update
            # - apt-get install -y unzip git
            - echo "Clone all the things!"
            - git tag -am "Tagging App for release ${BITBUCKET_BUILD_NUMBER}" v${BITBUCKET_BUILD_NUMBER}
            - git push origin v${BITBUCKET_BUILD_NUMBER}
    master:
      - step:
          name: build and test
          caches:
          - node
          script: # Modify the commands below to build your repository.
          - yarn install
          - yarn build
          - yarn test:cov
      - step:
          name: deploy with tag
          script:
            # - apt-get update
            # - apt-get install -y unzip git
            - echo "Clone all the things!"
            - git tag -am "Tagging App for release ${BITBUCKET_BUILD_NUMBER}" release${BITBUCKET_BUILD_NUMBER}
            - git push origin release${BITBUCKET_BUILD_NUMBER}
